name: Pipelines for ECS Project

on:
  push:
    # Uncomment if you want to limit the workflow to specific files:
    # paths:
    #  - 'Dockerfile'
    #  - 'docker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
            cd app
            ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ecs-project:latest
            echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
            docker build -t $ECR_URI .
            docker push $ECR_URI

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Export Secrets for Terraform
        run: |
          export TF_VAR_aws_access_key_id=$AWS_ACCESS_KEY_ID
          export TF_VAR_aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
          export TF_VAR_aws_region=$AWS_REGION

      - name: Terraform Init
        run: |
            cd infra
            terraform init

      - name: Terraform Validate
        run: |
            cd infra
            terraform validate

      - name: Terraform Plan
        run: |
            cd infra
            terraform plan -out=tfplan
