name: Pipelines for ECS Project
on:
  push:
   # paths:
    #  - 'Dockerfile'
    #  - 'docker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      -  name: Log in to Amazon ECR
         run: |
          aws ecr get-login-password --region ${{vars.AWS_REGION}} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com

      - name: Build Docker image
        run: |
            cd app
            IMAGE_TAG=$(git rev-parse --short HEAD)
            ECR_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com/ecs-project:$IMAGE_TAG
            echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
            docker build -t $ECR_URI .
            docker push $ECR_URI