name: Terraform Plan 

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.5.0  
    
      - name: Terraform Init
        run: |
            cd infra
            terraform init
    
      - name: Terraform Validate
        run: |
            cd infra
            terraform validate
    
      - name: Terraform Plan
        run: |
            cd infra
            terraform plan -out=tfplan
